#!/bin/sh
# Xsetup - run as root before the login dialog appears
# File: /usr/share/sddm/scripts/Xsetup
xrandr --output HDMI-1 --off --output HDMI-2 --mode 1920x1080 --pos 4480x0 --rotate normal --output DP-1 --primary --mode 2560x1080 --pos 1920x0 --rotate normal --output HDMI-3 --off --output DP-2 --mode 1920x1080 --pos 0x0 --rotate normal

