#!/usr/bin/env bash

## Copyright (C) 2020-2021 Aditya Shakya <adi1090x@gmail.com>
## Everyone is permitted to copy and distribute copies of this file under GNU-GPL3

# Config monitors
$HOME/.screenlayout/3monitor.sh

## Environtment
export PATH="${PATH}:$HOME/.config/bspwm/bin"

## Get colors from .Xresources -------------------------------#
xrdb ~/.Xresources
getcolors() {
	FOREGROUND=$(xrdb -query | grep 'foreground:'| awk '{print $NF}')
	BACKGROUND=$(xrdb -query | grep 'background:'| awk '{print $NF}')
	BLACK=$(xrdb -query | grep 'color0:'| awk '{print $NF}')
	RED=$(xrdb -query | grep 'color1:'| awk '{print $NF}')
	GREEN=$(xrdb -query | grep 'color2:'| awk '{print $NF}')
	YELLOW=$(xrdb -query | grep 'color3:'| awk '{print $NF}')
	BLUE=$(xrdb -query | grep 'color4:'| awk '{print $NF}')
	MAGENTA=$(xrdb -query | grep 'color5:'| awk '{print $NF}')
	CYAN=$(xrdb -query | grep 'color6:'| awk '{print $NF}')
	WHITE=$(xrdb -query | grep 'color7:'| awk '{print $NF}')
}
getcolors

## Configurations --------------------------------------------#
bspc monitor DP-0 -d '' '' ''
bspc monitor DVI-I-0 -d '' '' ''
bspc monitor DVI-D-0 -d '' 'ﭮ' '漣'

bspc config border_width 2
bspc config window_gap 10
bspc config split_ratio 0.50

bspc config focused_border_color "$BLUE" 
bspc config normal_border_color "$BACKGROUND"
bspc config active_border_color "$MAGENTA"
bspc config presel_feedback_color "$GREEN"

bspc config borderless_monocle false
bspc config gapless_monocle true
bspc config paddingless_monocle false
bspc config single_monocle false
bspc config focus_follows_pointer true

## Window rules ----------------------------------------------#

# Para descubrir classname de app
# xprop | grep -E WM_CLASS | awk '{print $4}'
# Y clickas en la ventana que sea
  
# Workspace 1 (Terminals)
declare -a terminal=(Alacritty Xfce4-terminal kitty)
for i in ${terminal[@]}; do
    bspc rule -a $i desktop='^1' follow=on focus=on; done
  
# Workspace 3 (Files)
declare -a filem=(dolphin Thunar Pcmanfm qBittorrent)
for i in ${filem[@]}; do
    bspc rule -a $i desktop='^3' follow=on focus=on; done
  
# Workspace 4 (Internet Browser)
declare -a web=(firefox Vivaldi-stable chromium)
for i in ${web[@]}; do
    bspc rule -a $i desktop='^4' follow=on focus=on; done
  
# Workspace 5 (Text Editor)
declare -a office=(code-oss obsidian Geany VSCodium DesktopEditors) 
for i in ${office[@]}; do
    bspc rule -a $i desktop='^5' follow=on focus=on; done
  
# Workspace 6 (Media)
declare -a media=(vlc ncmpcpp nuclear obs mpv mplayer lxmusic Inkscape)
for i in ${media[@]}; do
    bspc rule -a $i desktop='^6' follow=on focus=on; done
  
# Workspace 7 (Social)
declare -a social=(TelegramDesktop Mailspring)
for i in ${social[@]}; do
    bspc rule -a $i desktop='^7' follow=on focus=on; done

# Workspace 8 (Discord)
declare -a music=(discord)
for i in ${music[@]}; do
    bspc rule -a $i desktop='^8' follow=on focus=on; done
  
# Workspace 9 (Settings)
declare -a settings=(GParted KeePassXC Lxappearance Lxtask Lxrandr Arandr \
Pavucontrol Xfce4-settings-manager Nvidia-settings Local)
for i in ${settings[@]}; do
    bspc rule -a $i desktop='^9' follow=on focus=on; done
  
# Special rules
declare -a floating=(Alafloat yad-calendar Galculator Lxappearance Arandr \
Viewnior feh Nm-connection-editor Matplotlib Yad)
for i in ${floating[@]}; do
  bspc rule -a $i state=floating follow=on focus=on; done

bspc rule -a ncmpcpp state=pseudo_tiled follow=on focus=on

#bspc rule -a Conky state=floating manage=off
#bspc rule -a stalonetray state=floating manage=off

## Autostart -------------------------------------------------#

# Kill if already running
killall -9 sxhkd dunst xfce4-power-manager

# polkit agent
if [[ ! `pidof polkit-gnome-authentication-agent-1` ]]; then
	/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
fi

# Lauch keybindings daemon
sxhkd &

# Enable power management
xfce4-power-manager &

# Enable applets
nm-applet &

# Fix cursor
xsetroot -cursor_name left_ptr

# Restore wallpaper
#bash $HOME/.fehbg
nitrogen --restore

# KeePassXC
if [[ ! `pidof keepassxc` ]]; then
        secret-tool lookup keepass IL | keepassxc --pw-stdin ~/.config/keepassxc/IL.kdbx &
fi

# Start bspwm scripts
bspcolors 
bspbar
bspcomp
bspdunst

